---
- name: Add present credentials
  solita_jenkins_credential:
    solita_jenkins_cli: "{{ solita_jenkins_cli }}"
    id: "{{ item.key }}"
    name: "{{ item.value.name }}"
    password: "{{ item.value.password }}"
    description: "{{ item.value.description }}"
  with_dict: "{{ solita_jenkins_credentials }}"
  no_log: yes
