---
- name: Add present credentials
  solita_jenkins_credential:
    solita_jenkins_cli: "{{ solita_jenkins_cli }}"
    id: "{{ item.key }}"
    username: "{{ item.value.username }}"
    password: "{{ item.value.password }}"
    description: "{{ item.value.description | default('') }}"
  with_dict: "{{ solita_jenkins_credentials }}"

- name: Remove absent credentials
  solita_jenkins_credential:
    solita_jenkins_cli: "{{ solita_jenkins_cli }}"
    id: "{{ item }}"
    state: absent
  with_items: "{{ solita_jenkins_absent_credentials }}"
