---
- name: Create an SSH key for the Unix user
  user: name={{ ansible_user_id }} generate_ssh_key=yes
  register: user

- set_fact:
    solita_jenkins_public_key: "{{ user.ssh_public_key }}"

- name: Install matrix-auth plugin and its dependencies
  become: yes
  get_url:
    url: "http://updates.jenkins-ci.org/latest/{{ item }}.hpi"
    dest: /var/lib/jenkins/plugins
    owner: jenkins
    group: jenkins
    mode: 0755
  register: matrix_auth_plugin
  with_items:
    - icon-shim
    - matrix-auth

- name: Copy Jenkins security realm configuration
  become: yes
  template:
    src: solita_jenkins_security_realm.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/solita_jenkins_security_realm.groovy
    owner: jenkins
    group: jenkins
    mode: 0700
  register: security_realm

- name: Set the TCP port for JNLP agents
  become: yes
  lineinfile:
    dest: /var/lib/jenkins/config.xml
    regexp: "^(\\s*)<slaveAgentPort>"
    line: "\\1<slaveAgentPort>{{ solita_jenkins_jnlp_port }}</slaveAgentPort>"
    backrefs: yes
  register: jnlp_port

- include: restart.yml
  when: (matrix_auth_plugin | changed) or (security_realm | changed) or (jnlp_port | changed)

- name: Check that user variables are only used with solita_jenkins_security_realm='jenkins'
  fail: msg="User variables are only allowed with solita_jenkins_security_realm='jenkins'"
  when: ({{ item }} | length > 0) and ((solita_jenkins_security_realm | default(None)) != 'jenkins')
  with_items:
    - solita_jenkins_users
    - solita_jenkins_absent_users

- name: Add present Jenkins users
  solita_jenkins_user:
    jenkins_url: "{{ solita_jenkins_url }}"
    name: "{{ item }}"
    password: "{{ lookup('password', solita_jenkins_password_dir + '/' + item) }}"
  with_items: "{{ solita_jenkins_users }}"

- name: Remove absent Jenkins users
  solita_jenkins_user:
    jenkins_url: "{{ solita_jenkins_url }}"
    name: "{{ item }}"
    state: absent
  with_items: "{{ solita_jenkins_absent_users }}"
